export interface Repositoy {
    allow_forking: boolean,
    archive_url: string
    archived: boolean,
    assignees_url: string
    blobs_url: string
    branches_url: string
    clone_url: string,
    collaborators_url: string
    comments_url: string
    commits_url: string
    compare_url: string,
    contents_url: string
    contributors_url: string,
    default_branch: string
    deployments_url: string,
    disabled: boolean,
    downloads_url: string
    foks: string,
    git_commits_url: string,
    git_refs_url: string,
    git_tags_url: string,
    git_url: string,
    has_discussions: boolean,
    has_downloads: boolean,
    id: number
    is_template: boolean,
    language: string,
    name: string,
    open_issues: 0
    open_issues_count: 0
    owner: Object,
    private: boolean,
    pulls_url: string
    pushed_at: string,
    releases_url: string
    size: number,
    stargazers_count: number,
    updated_at: string,
    description: string,
    url:string ,
} 